<a href="https://colab.research.google.com/github/rizzie42/MCREU_2023Summer/blob/main/MC_REU_2023.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Place all library importation code in the cell below

In [ ]:
import pandas as pd
import math
from scipy.stats import f_oneway, kruskal, chi2_contingency

Load data

In [ ]:
!gdown 1PwDdEQPeBrXmStmlgbCvUGpGolsdaf3M

Downloading...
From: https://drive.google.com/uc?id=1PwDdEQPeBrXmStmlgbCvUGpGolsdaf3M
To: /content/patient.csv
100% 12.8M/12.8M [00:00<00:00, 185MB/s]

In [ ]:
!gdown 1wjpmrV6KfnSdluYHyoU1egMQf8kXWK6x

Downloading...
From: https://drive.google.com/uc?id=1wjpmrV6KfnSdluYHyoU1egMQf8kXWK6x
To: /content/tumor.csv
100% 12.9M/12.9M [00:00<00:00, 170MB/s]

Put data into pandas dataframe

In [ ]:
df1 = pd.read_csv("patient.csv")
df2 = pd.read_csv("tumor.csv")

<ipython-input-141-b5b1f4fa7bed>:2: DtypeWarning: Columns (6,8,9,10,11) have mixed types. Specify dtype option on import or set low_memory=False.
  df2 = pd.read_csv("tumor.csv")

Display original data

In [ ]:
df1

,patient_id,sex,race,ethnicity,marital_status,year_of_birth,reason_yob_missing,month_year_death,death_date_source_id,patient_regional_location,source_id
0,ugD,F,Unknown,Unknown,Married,1955.0,Present,NaN,NaN,Ex-US,EHR
1,uwD,M,Unknown,Unknown,Single,1982.0,Present,NaN,NaN,Ex-US,EHR
2,uAE,M,Unknown,Unknown,Married,1959.0,Present,NaN,NaN,Ex-US,EHR
3,uQE,F,Unknown,Unknown,Married,1966.0,Present,NaN,NaN,Ex-US,EHR
4,ugE,F,Unknown,Unknown,Married,1963.0,Present,NaN,NaN,Ex-US,EHR
...,...,...,...,...,...,...,...,...,...,...,...
138396,Ow,F,Unknown,Unknown,Single,1958.0,Present,NaN,NaN,Ex-US,EHR
138397,OAB,M,Unknown,Unknown,Married,1955.0,Present,NaN,NaN,Ex-US,EHR
138398,OQB,F,Unknown,Unknown,Single,1970.0,Present,NaN,NaN,Ex-US,EHR
138399,OgB,M,Unknown,Unknown,Married,1959.0,Present,NaN,NaN,Ex-US,EHR
138400,OwB,M,Unknown,Unknown,Married,1948.0,Present,202204.0,EHR,Ex-US,EHR

In [ ]:
df2

,patient_id,diagnosis_date,observation_date,tumor_site_code_system,tumor_site_code,morphology_code_system,morphology_code,stage_code_system,stage_code,tumor_size,number_of_lymph_nodes,metastatic,derived_by_TriNetX,source_id
0,YgGB,20210929,20210929,ICD-O,C71.2,ICD-O,9440/3,TriNetX - Oncology Stage,NaN,NaN,NaN,NaN,F,Cancer Registry
1,YANB,20210901,20210901,ICD-O,C71.1,ICD-O,9440/3,TriNetX - Oncology Stage,NaN,NaN,NaN,NaN,F,Cancer Registry
2,YQVB,20210108,20210108,ICD-O,C71.2,ICD-O,9440/3,TriNetX - Oncology Stage,NaN,NaN,NaN,NaN,F,Cancer Registry
3,YgVB,20210609,20210609,ICD-O,C71.3,ICD-O,9440/3,TriNetX - Oncology Stage,NaN,NaN,NaN,NaN,F,Cancer Registry
4,YQWB,20210508,20210508,ICD-O,C71.2,ICD-O,9440/3,TriNetX - Oncology Stage,NaN,NaN,NaN,NaN,F,Cancer Registry
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
115897,7wXr,20161010,20161010,ICD-O,C50.9,ICD-O,NaN,TriNetX - Oncology Stage,NaN,NaN,NaN,NaN,F,TriNetX
115898,7wXr,20161005,20161005,ICD-O,C50.9,ICD-O,NaN,TriNetX - Oncology Stage,NaN,NaN,NaN,NaN,F,TriNetX
115899,7wXr,20161221,20161221,ICD-O,C50.9,ICD-O,NaN,TriNetX - Oncology Stage,NaN,NaN,NaN,NaN,F,TriNetX
115900,7wXr,20161223,20161223,ICD-O,C50.9,ICD-O,NaN,TriNetX - Oncology Stage,NaN,NaN,NaN,NaN,F,TriNetX
115901,7Aor,20161123,20161123,ICD-O,C50.4,ICD-O,NaN,TriNetX - Oncology Stage,NaN,NaN,NaN,NaN,F,TriNetX

Merge data (inner join)

In [ ]:
df = pd.merge(df1, df2, 'inner', on = "patient_id")

In [ ]:
df

,patient_id,sex,race,ethnicity,marital_status,year_of_birth,reason_yob_missing,month_year_death,death_date_source_id,patient_regional_location,...,tumor_site_code,morphology_code_system,morphology_code,stage_code_system,stage_code,tumor_size,number_of_lymph_nodes,metastatic,derived_by_TriNetX,source_id_y
0,YgGB,M,White,Not Hispanic or Latino,Married,1975.0,Present,202212.0,Death Registry,South,...,C71.2,ICD-O,9440/3,TriNetX - Oncology Stage,NaN,NaN,NaN,NaN,F,Cancer Registry
1,YANB,M,White,Not Hispanic or Latino,Married,1937.0,Present,202112.0,EHR,South,...,C71.1,ICD-O,9440/3,TriNetX - Oncology Stage,NaN,NaN,NaN,NaN,F,Cancer Registry
2,YQVB,M,White,Not Hispanic or Latino,Single,1953.0,Present,202108.0,Death Registry,South,...,C71.2,ICD-O,9440/3,TriNetX - Oncology Stage,NaN,NaN,NaN,NaN,F,Cancer Registry
3,YgVB,M,White,Hispanic or Latino,Married,1932.0,Present,202108.0,Death Registry,South,...,C71.3,ICD-O,9440/3,TriNetX - Oncology Stage,NaN,NaN,NaN,NaN,F,Cancer Registry
4,YQWB,M,White,Not Hispanic or Latino,Single,1952.0,Present,202112.0,Death Registry,South,...,C71.2,ICD-O,9440/3,TriNetX - Oncology Stage,NaN,NaN,NaN,NaN,F,Cancer Registry
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
115897,WgD,F,Unknown,Unknown,Unknown,1935.0,Present,202105.0,EHR,Ex-US,...,C71.1,ICD-O,9400/3,TriNetX - Oncology Stage,S4B,NaN,TNM_N1c,TNM_M1c,F,EHR
115898,WwD,F,Unknown,Unknown,Unknown,1944.0,Present,201903.0,EHR,Ex-US,...,C71.9,ICD-O,9440/3,TriNetX - Oncology Stage,S4B,NaN,TNM_N1c,TNM_M1c,F,EHR
115899,WAE,F,Unknown,Unknown,Unknown,1963.0,Present,NaN,NaN,Ex-US,...,C71.8,ICD-O,9451/3,TriNetX - Oncology Stage,NaN,NaN,NaN,NaN,F,EHR
115900,WQE,F,Unknown,Unknown,Unknown,1943.0,Present,202107.0,EHR,Ex-US,...,C71.9,ICD-O,9440/3,TriNetX - Oncology Stage,S4B,NaN,TNM_N1c,TNM_M1c,F,EHR
115901,WwE,F,Unknown,Unknown,Unknown,1950.0,Present,202109.0,EHR,Ex-US,...,C37.9,ICD-O,8082/3,TriNetX - Oncology Stage,NaN,NaN,NaN,NaN,F,EHR

Drop certain features

In [ ]:
df = df.drop(["patient_id", "death_date_source_id", 'source_id_x', 'diagnosis_date',
              'observation_date', 'derived_by_TriNetX', 'source_id_y',
              "tumor_site_code_system", "morphology_code_system", "morphology_code",
              "stage_code_system", "stage_code", "tumor_size",
              "number_of_lymph_nodes", "metastatic"], axis = 1)

In [ ]:
df

,sex,race,ethnicity,marital_status,year_of_birth,reason_yob_missing,month_year_death,patient_regional_location,tumor_site_code
0,M,White,Not Hispanic or Latino,Married,1975.0,Present,202212.0,South,C71.2
1,M,White,Not Hispanic or Latino,Married,1937.0,Present,202112.0,South,C71.1
2,M,White,Not Hispanic or Latino,Single,1953.0,Present,202108.0,South,C71.2
3,M,White,Hispanic or Latino,Married,1932.0,Present,202108.0,South,C71.3
4,M,White,Not Hispanic or Latino,Single,1952.0,Present,202112.0,South,C71.2
...,...,...,...,...,...,...,...,...,...
115897,F,Unknown,Unknown,Unknown,1935.0,Present,202105.0,Ex-US,C71.1
115898,F,Unknown,Unknown,Unknown,1944.0,Present,201903.0,Ex-US,C71.9
115899,F,Unknown,Unknown,Unknown,1963.0,Present,NaN,Ex-US,C71.8
115900,F,Unknown,Unknown,Unknown,1943.0,Present,202107.0,Ex-US,C71.9
115901,F,Unknown,Unknown,Unknown,1950.0,Present,202109.0,Ex-US,C37.9

Preprocess Data (Discretization)

In [ ]:
# Sex: M = 0, F = 1
df['sex'] = df['sex'].replace(['M', 'F'], [0, 1])

In [ ]:
# Race: Unknown = 0, White = 1, Asian = 2, Black or African American = 3, American Indian or Alaska Native = 4, Native Hawaiian or Other Pacific Islander = 5
df['race'] = df['race'].replace(['Unknown', 'White', 'Asian', 'Black or African American', 'American Indian or Alaska Native', 'Native Hawaiian or Other Pacific Islander'], [0, 1, 2, 3, 4, 5])

In [ ]:
# Ethnicity: Unknown = 0, Not Hispanic or Latino = 1, Hispanic or Latino = 2
df['ethnicity'] = df['ethnicity'].replace(['Unknown', 'Not Hispanic or Latino', 'Hispanic or Latino'], [0, 1, 2])

In [ ]:
# Marital_Status: Unknown = 0, Married = 1, Single = 2
df['marital_status'] = df['marital_status'].replace(['Unknown', 'Married', 'Single'], [0, 1, 2])

In [ ]:
# Age: 2023 - year of birth
df = df.rename(columns = {'year_of_birth': 'age'})
df['age'] = 2023 - df['age']

# Remove patients without age
df = df[df['reason_yob_missing'] == 'Present']
df = df.drop(['reason_yob_missing'], axis = 1)

In [ ]:
# Status: Dead = 0, Alive = 1
df = df.rename(columns = {'month_year_death': 'status'})

for i in df.status.unique():
  if math.isnan(i):
    pass

  else:
    df.loc[df['status'] == i, 'status'] = 0

df['status'] = df['status'].fillna(1)

In [ ]:
# Region: Unknown = 0, Northeast = 1, South = 2, Midwest = 3, West = 4, Ex-US = 5
df['patient_regional_location'] = df['patient_regional_location'].replace(['Unknown', 'Northeast', 'South', 'Midwest', 'West', 'Ex-US'], [0, 1, 2, 3, 4, 5])

In [ ]:
# Tumor: Other tumor = 0, Brain tumor = 1
df = df.replace({'tumor_site_code': r'^C70'}, {'tumor_site_code': 1}, regex=True)
df = df.replace({'tumor_site_code': r'^C71'}, {'tumor_site_code': 1}, regex=True)
df = df.replace({'tumor_site_code': r'^C72'}, {'tumor_site_code': 1}, regex=True)
df.loc[df['tumor_site_code'] != 1, 'tumor_site_code'] = 0

In [ ]:
df

,sex,race,ethnicity,marital_status,age,status,patient_regional_location,tumor_site_code
0,0.0,1,1,1,48.0,0.0,2,1
1,0.0,1,1,1,86.0,0.0,2,1
2,0.0,1,1,2,70.0,0.0,2,1
3,0.0,1,2,1,91.0,0.0,2,1
4,0.0,1,1,2,71.0,0.0,2,1
...,...,...,...,...,...,...,...,...
115897,1.0,0,0,0,88.0,0.0,5,1
115898,1.0,0,0,0,79.0,0.0,5,1
115899,1.0,0,0,0,60.0,1.0,5,1
115900,1.0,0,0,0,80.0,0.0,5,1
115901,1.0,0,0,0,73.0,0.0,5,0

Restrict Patient

In [ ]:
# Retain only US patients
df = df[df['patient_regional_location'] != 0]
df = df[df['patient_regional_location'] != 5]

In [ ]:
df = df.dropna()

Statistical Analysis (Rizzie)

In [ ]:
# Mean Value
mean_value = df.mean()
print(mean_value)

sex                           0.848868
race                          1.189817
ethnicity                     0.880282
marital_status                0.598883
age                          62.163476
status                        0.529284
patient_regional_location     2.033344
tumor_site_code               0.182689
dtype: float64

In [ ]:
# Geometric Mean Value
#geometric_mean_values = df.apply(lambda x: math.pow(x.prod(), 1/len(x)), axis=0)
#print(geometric_mean_values)

# The tumor_site_code column won't work with the gmean function, possibly due to incompatible data type
from scipy.stats import gmean
geometric_mean_values = df.iloc[:, :-1].apply(gmean, axis=0)
print(geometric_mean_values)

sex                           0.000000
race                          0.000000
ethnicity                     0.000000
marital_status                0.000000
age                          59.941425
status                        0.000000
patient_regional_location     1.816462
dtype: float64

In [ ]:
# Percentage (calculate the coverage of each unique value in an attribute (except age))
# Example: Male: 51%, Female: 49%
column_percentages = (df.sum()/ df.sum().sum() )*100
print(column_percentages)

sex                           1.240552
race                          1.738822
ethnicity                     1.286461
marital_status                 0.87522
age                          90.846887
status                        0.773506
patient_regional_location     2.971567
tumor_site_code               0.266986
dtype: object

In [ ]:
# Percentage (split the age into 10 groups and calculate the coverage of each group)
# Example: 0-10: 1%, 11-20: 3%, etc.
age_groups = pd.cut(df['age'], bins = 10)
coverage = age_groups.value_counts()/ len(df)*100
print(coverage)

(60.5, 72.0]      33.783216
(49.0, 60.5]      20.970033
(72.0, 83.5]      19.916931
(37.5, 49.0]      13.483096
(83.5, 95.0]       5.500424
(26.0, 37.5]       3.980171
(14.5, 26.0]       1.385378
(2.885, 14.5]      0.491269
(95.0, 106.5]      0.447501
(106.5, 118.0]     0.041981
Name: age, dtype: float64

In [ ]:
# ANOVA / Kruskal - Wallis (continuous - categorical)
F, anova_p_value = f_oneway(df['status'], df['tumor_site_code'])
print(anova_p_value)
print(F)

0.0
33752.2204350365

In [ ]:
from scipy.stats.contingency import expected_freq
# Chi Square (categorical - categorical)
# Age is a continuous feature, not a categorical feature

contigency_table = pd.crosstab(df['age'], df['tumor_site_code'])
chi2, p_value, dof, expected_freq = chi2_contingency(contigency_table)
print(p_value)

0.0

Additional SA

In [ ]:
print("Male count: " + str(len(df[df['sex'] == 0])))
print("Female count: " + str(len(df[df['sex'] == 1])))

Male count: 16920
Female count: 95035

In [ ]:
print("Northeast count: " + str(len(df[df['patient_regional_location'] == 1])))
print("South count: " + str(len(df[df['patient_regional_location'] == 2])))
print("Midwest count: " + str(len(df[df['patient_regional_location'] == 3])))
print("West count: " + str(len(df[df['patient_regional_location'] == 4])))

Northeast count: 38466
South count: 41682
Midwest count: 21415
West count: 10392

In [ ]:
R = []

for i in df.race.unique():
  R.append(len(df[df['race'] == i]))

print(R)

[78956, 14347, 15695, 600, 2340, 17]

In [ ]:
print("Positive count: " + str(len(df[df['tumor_site_code'] == 1])))
print("Negative count: " + str(len(df[df['tumor_site_code'] == 0])))

Positive count: 20453
Negative count: 91502

In [ ]:
Results = []

for i in df.sex.unique():
  Result = []

  Result.append(str(i)) # Create label for each sex group
  Result.append(str(len(df[(df['sex'] == i) & (df['tumor_site_code'] == 1)]))) # Count number of brain cancer patients for each sex group
  Result.append(str(len(df[(df['sex'] == i) & (df['tumor_site_code'] == 1) & (df['status'] == 0)])))# Count number of deceased brain cancer patients for each sex group

  Results.append(Result)

Results

[['0.0', '11289', '5556'], ['1.0', '9164', '3976']]

sex, count_of_patient, count_of_deceased_patient

In [ ]:
Results = []

for i in df.patient_regional_location.unique():
  Result = []

  Result.append(str(i)) # Create label for each region group
  Result.append(str(len(df[(df['patient_regional_location'] == i) & (df['tumor_site_code'] == 1)]))) # Count number of brain cancer patients for each region group
  Result.append(str(len(df[(df['patient_regional_location'] == i) & (df['tumor_site_code'] == 1) & (df['status'] == 0)])))# Count number of deceased brain cancer patients for each region group

  Results.append(Result)

Results

[['2', '8919', '3398'],
 ['1', '5483', '2838'],
 ['4', '34', '8'],
 ['3', '6017', '3288']]

regional_location_group, count_of_patient, count_of_deceased_patient

In [ ]:
Results = []

for i in df.race.unique():
  Result = []

  Result.append(str(i)) # Create label for each race group
  Result.append(str(len(df[(df['race'] == i) & (df['tumor_site_code'] == 1)]))) # Count number of brain cancer patients for each race group
  Result.append(str(len(df[(df['race'] == i) & (df['tumor_site_code'] == 1) & (df['status'] == 0)])))# Count number of deceased brain cancer patients for each race group

  Results.append(Result)

Results

[['1', '16042', '7618'],
 ['0', '2529', '1185'],
 ['3', '1535', '603'],
 ['4', '50', '20'],
 ['2', '283', '102'],
 ['5', '14', '4']]

race, count_of_patient, count_of_deceased_patient

In [ ]:
df_tumor = df[['status', 'tumor_site_code']].join(pd.DataFrame(age_groups.rename("age_group")))

Results = []

for i in df_tumor.age_group.unique():
  Result = []

  Result.append(str(i)) # Create label for each age group
  Result.append(str(len(df_tumor[(df_tumor['age_group'] == i) & (df_tumor['tumor_site_code'] == 1)]))) # Count number of brain cancer patients for each age group
  Result.append(str(len(df_tumor[(df_tumor['age_group'] == i) & (df_tumor['tumor_site_code'] == 1) & (df_tumor['status'] == 0)])))# Count number of deceased brain cancer patients for each age group

  Results.append(Result)

Results

[['(37.5, 49.0]', '2329', '662'],
 ['(83.5, 95.0]', '2049', '1408'],
 ['(60.5, 72.0]', '5075', '2686'],
 ['(14.5, 26.0]', '1338', '293'],
 ['(26.0, 37.5]', '1632', '324'],
 ['(72.0, 83.5]', '4289', '2508'],
 ['(49.0, 60.5]', '2842', '1138'],
 ['(95.0, 106.5]', '350', '350'],
 ['(2.885, 14.5]', '505', '119'],
 ['(106.5, 118.0]', '44', '44']]

In [ ]:
age_groups.value_counts()

(60.5, 72.0]      37822
(49.0, 60.5]      23477
(72.0, 83.5]      22298
(37.5, 49.0]      15095
(83.5, 95.0]       6158
(26.0, 37.5]       4456
(14.5, 26.0]       1551
(2.885, 14.5]       550
(95.0, 106.5]       501
(106.5, 118.0]       47
Name: age, dtype: int64